name: vsoch
description: vanessa villamia sochat
meta_description: "vanessa villamia sochat"

aboutPage: true

highlighter:      rouge

paginate: 20
paginate_path: "page:num"
baseurl: /v1/
domain_name: 'vsoch.github.io'
# google_analytics: 'UA-67197905-1'
disqus: true
disqus_shortname: 'vsoch'

# SEO details
twitter:
  username: vsoch
logo: /assets/images/avatar.png
gems:
  - jekyll-seo-tag
  - jekyll-paginate

# Details for the RSS feed generator
url:            'https://vsoch.github.io'
author:         'vsoch'
authorTwitter:  'vsoch'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
